In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)
import random

ModuleNotFoundError: No module named 'torch'

In [110]:
#init a tensor (scalar)
scalar = torch.tensor(7)
scalar
#Returns tensor(7)

tensor(7)

In [111]:
scalar.ndim
#returns 0, it is a 0 dimensional vector

0

In [112]:
scalar.item()
# returns 7. Get tensor back as python int

7

In [113]:
#Vector
vector = torch.tensor([7,7])
vector
#tensor([7, 7])

tensor([7, 7])

In [114]:
vector.ndim
# returns 1. think of dimensions of a tensor as the number of nested square brackets

1

In [115]:
vector.shape
#torch.Size([2])

torch.Size([2])

In [116]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX.shape, MATRIX.ndim
#(torch.Size([2, 2]), 2)

(torch.Size([2, 2]), 2)

In [117]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,5,4]],
                       [[5,6,8],
                        [9,10,11],
                        [13,14,15]]])
TENSOR.shape, TENSOR.ndim
#(torch.Size([1, 3, 3]), 3)

(torch.Size([2, 3, 3]), 3)

In [118]:
TENSOR


tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [ 2,  5,  4]],

        [[ 5,  6,  8],
         [ 9, 10, 11],
         [13, 14, 15]]])

### CH13 - Creating Random Tensors




In [119]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor
#0.00333,0.83908,0.47228,0.84238
#0.69856,0.58338,0.54370,0.24816
#0.52106,0.59562,0.00936,0.40265



tensor([[0.8883, 0.6868, 0.1886, 0.9347],
        [0.2212, 0.1300, 0.2161, 0.0521],
        [0.4270, 0.2372, 0.6401, 0.6823]])

In [120]:
# Create a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, color channels (RGB)
random_image_size_tensor.shape, random_image_size_tensor.ndim
# (torch.Size([224, 224, 3]), 3)

(torch.Size([224, 224, 3]), 3)

In [121]:
# Tensor of Zeros and Ones
zero = torch.zeros(size=(3,4))
zero
# 0.00000,0.00000,0.00000,0.00000
# 0.00000,0.00000,0.00000,0.00000
# 0.00000,0.00000,0.00000,0.00000



tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [122]:
# Anything multiplied by zero matrix is 0 matrix
zero * random_tensor
# 0.00000,0.00000,0.00000,0.00000
# 0.00000,0.00000,0.00000,0.00000
# 0.00000,0.00000,0.00000,0.00000


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [123]:
# Anything Multiplied by a one matrix is itself
ones = torch.ones(size=(3,4))
ones
# 1.00000,1.00000,1.00000,1.00000
# 1.00000,1.00000,1.00000,1.00000
# 1.00000,1.00000,1.00000,1.00000

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [124]:
# default data type is torch.float32
ones.dtype
#torch.float32

torch.float32

In [125]:
# Use torch.arange() to create a tensor of len 10 in order
one_to_ten = torch.arange(0,10)
# tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
torch.arange(start=0, end=77, step=11)
# tensor([ 0, 11, 22, 33, 44, 55, 66])

tensor([ 0, 11, 22, 33, 44, 55, 66])

In [127]:
# Creating tensors like (copy attributes of another tensor)
ten_zeros = torch.full_like(input = one_to_ten, fill_value = random.randint(0,5))
ten_zeros
# tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [128]:
# Float 32 tensor is default data type
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None,        # Data Type (int, float32, float16, etc)
                               device=None,         # Default is CPU
                               requires_grad=False) # Track the gradient of the tensor as it goes through certain operations. worry about later
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [129]:
# Refactor float_32 tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor
# tensor([3., 6., 9.], dtype=torch.float16)

tensor([3., 6., 9.], dtype=torch.float16)

In [130]:
# multiplying a 16 x 32 converts the output to a 32
x = float_16_tensor * float_32_tensor
x, x.dtype
# (tensor([ 9., 36., 81.]), torch.float32)

(tensor([ 9., 36., 81.]), torch.float32)

In [131]:
# Operations on different dtypes doesnt always work
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [132]:
# Getting Information from tensors
# e.g. Shape, Datatype, and Device
float_16_tensor.shape, float_16_tensor.ndim, float_16_tensor.device
# (torch.Size([3]), 1, device(type='cpu'))

(torch.Size([3]), 1, device(type='cpu'))

In [133]:
some_tensor = torch.rand(3,4, dtype=torch.float16)
some_tensor
# 0.96271,0.78899,0.16476,0.17654
# 0.40736,0.24902,0.94571,0.67510
# 0.79564,0.68495,0.79836,0.89421


tensor([[0.5107, 0.8521, 0.5615, 0.1895],
        [0.5542, 0.8271, 0.3540, 0.6353],
        [0.4707, 0.0581, 0.3120, 0.0786]], dtype=torch.float16)

In [134]:
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")
# Datatype of tensor: torch.float32
# Shape of tensor: torch.Size([3, 4])
# Device of tensor: cpu

Datatype of tensor: torch.float16
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


In [135]:
tensor = torch.tensor([1,2,3])
tensor + 10, tensor + 100
# (tensor([11, 12, 13]), tensor([101, 102, 103]))

(tensor([11, 12, 13]), tensor([101, 102, 103]))

In [136]:
tensor * 10, (tensor * 10)// 2, tensor - 10
# (tensor([10, 20, 30]), tensor([ 5, 10, 15]), tensor([-9, -8, -7]))

(tensor([10, 20, 30]), tensor([ 5, 10, 15]), tensor([-9, -8, -7]))

In [137]:
#In-built functions. Usually just use python operators
torch.mul(tensor, 10), torch.add(tensor,10)
#(tensor([10, 20, 30]), tensor([11, 12, 13]))

(tensor([10, 20, 30]), tensor([11, 12, 13]))

In [138]:
# Matrix Multiplication (element wise)
print(tensor, "*", tensor, "=", tensor * tensor)
# tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])

tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


In [139]:
# Normal Matrix Multiplication (matmul)
torch.matmul(tensor, tensor)
# tensor(14)

tensor(14)

In [140]:
#Remember inner dimensions must match, result is the outer dimensions
x,y = torch.rand(4,3),torch.rand(3,2)
z = torch.matmul(x,y)
z.shape, z.ndim
#(torch.Size([4, 2]), 2)

(torch.Size([4, 2]), 2)

In [141]:
#Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         ])
torch.mm(tensor_A, tensor_B)   #torch.mm is the same as torch.matmul

tensor([[ 23,  32],
        [ 53,  74],
        [ 83, 116]])

In [142]:
# A Transpose switches the dimensions of a matrix
tensor_B.T
# 7,8,9
# 10,11,12


tensor([[ 7,  8],
        [10, 11]])

In [143]:
# We can now multiply A and B
torch.mm(tensor_A, tensor_B.T)
# 27,30,33
# 61,68,75
# 95,106,117


tensor([[ 27,  30],
        [ 61,  68],
        [ 95, 106]])

In [144]:
x = torch.arange(0,100,10)
torch.min(x), torch.max(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(0), tensor(90), tensor(45.), tensor(450))

In [145]:
x.dtype
#torch.int64

torch.int64

In [146]:
torch.mean(x.type(torch.float32))
#tensor(45.)   now it works

tensor(45.)

In [147]:
x = torch.arange(0,100,10)
torch.min(x), torch.max(x), torch.mean(x.type(torch.float32)), torch.sum(x)
#(tensor(0), tensor(90), tensor(45.), tensor(450))

(tensor(0), tensor(90), tensor(45.), tensor(450))

In [148]:
# Find the index of the min and max with argmin and argmax
torch.argmin(x.type(torch.float32)), torch.argmax(x.type(torch.float32))
#(tensor(0), tensor(9))

(tensor(0), tensor(9))

In [149]:
x = torch.arange(1., 10.)
x, x.shape
# (tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [150]:
# dimensions must be compatible with original dimensions
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape
# (tensor([[1., 2., 3.],
#          [4., 5., 6.],
#          [7., 8., 9.]]),
#  torch.Size([3, 3]))

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [151]:
# Change the view (similar to reshape. however, z shares memory with x)
# thus, changing z changes x
z = x.view(3,3)
z, z.shape
# (tensor([[1., 2., 3.],
#          [4., 5., 6.],
#          [7., 8., 9.]]),
#  torch.Size([3, 3]))

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [152]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked
# 1.00000,2.00000,3.00000,4.00000,5.00000,6.00000,7.00000,8.00000,9.00000
# 1.00000,2.00000,3.00000,4.00000,5.00000,6.00000,7.00000,8.00000,9.00000
# 1.00000,2.00000,3.00000,4.00000,5.00000,6.00000,7.00000,8.00000,9.00000
# 1.00000,2.00000,3.00000,4.00000,5.00000,6.00000,7.00000,8.00000,9.00000


tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [157]:
x_reshaped
# tensor([[[1., 2., 3.],
#          [4., 5., 6.],
#          [7., 8., 9.]]])

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

In [160]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])
Previous shape: torch.Size([1, 3, 3])

New tensor: tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
New shape: torch.Size([3, 3])


In [166]:
#Unsqueeze the previous squeeze
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

#Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")
# Previous target: tensor([[1., 2., 3.],
#         [4., 5., 6.],
#         [7., 8., 9.]])
# Previous shape: torch.Size([3, 3])
#
# New tensor: tensor([[[1., 2., 3.],
#          [4., 5., 6.],
#          [7., 8., 9.]]])
# New shape: torch.Size([1, 3, 3])

Previous target: tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
Previous shape: torch.Size([3, 3])

New tensor: tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])
New shape: torch.Size([1, 3, 3])


In [172]:
x_original = torch.rand(size=(224,224,3))  # Height, Width, color_channels of image data

#Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # Shifts axis 0 to 1, 1 to 2, and 2 to 0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") #[color channels, height, width]
# Previous shape: torch.Size([224, 224, 3])
# New shape: torch.Size([3, 224, 224])
x_permuted


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


tensor([[[0.9901, 0.7499, 0.2933,  ..., 0.9308, 0.7500, 0.2643],
         [0.5838, 0.6410, 0.2402,  ..., 0.6947, 0.9368, 0.2405],
         [0.2173, 0.5879, 0.6467,  ..., 0.1865, 0.8878, 0.8970],
         ...,
         [0.3409, 0.1038, 0.5731,  ..., 0.3703, 0.2952, 0.3661],
         [0.9795, 0.3634, 0.7047,  ..., 0.0095, 0.8800, 0.2111],
         [0.8293, 0.3351, 0.2470,  ..., 0.6382, 0.1949, 0.5463]],

        [[0.5907, 0.0126, 0.7461,  ..., 0.1411, 0.2088, 0.5495],
         [0.9296, 0.7756, 0.6974,  ..., 0.2369, 0.2810, 0.7557],
         [0.8547, 0.0636, 0.5705,  ..., 0.5641, 0.5164, 0.6574],
         ...,
         [0.5773, 0.7921, 0.0303,  ..., 0.3019, 0.5313, 0.7833],
         [0.6453, 0.1968, 0.5427,  ..., 0.0681, 0.3705, 0.7459],
         [0.0322, 0.8438, 0.0878,  ..., 0.8123, 0.3712, 0.7978]],

        [[0.5055, 0.0984, 0.8524,  ..., 0.3516, 0.7064, 0.1936],
         [0.0314, 0.1024, 0.5946,  ..., 0.3499, 0.5834, 0.0027],
         [0.8135, 0.2329, 0.0736,  ..., 0.9390, 0.8077, 0.

In [175]:
x_original[0,0,0] = 69
x_permuted

tensor([[[6.9000e+01, 7.4994e-01, 2.9329e-01,  ..., 9.3076e-01,
          7.5004e-01, 2.6431e-01],
         [5.8383e-01, 6.4098e-01, 2.4019e-01,  ..., 6.9472e-01,
          9.3684e-01, 2.4050e-01],
         [2.1733e-01, 5.8791e-01, 6.4671e-01,  ..., 1.8648e-01,
          8.8785e-01, 8.9698e-01],
         ...,
         [3.4085e-01, 1.0381e-01, 5.7308e-01,  ..., 3.7029e-01,
          2.9516e-01, 3.6615e-01],
         [9.7947e-01, 3.6338e-01, 7.0475e-01,  ..., 9.5237e-03,
          8.8004e-01, 2.1105e-01],
         [8.2933e-01, 3.3511e-01, 2.4695e-01,  ..., 6.3825e-01,
          1.9489e-01, 5.4625e-01]],

        [[5.9072e-01, 1.2577e-02, 7.4608e-01,  ..., 1.4107e-01,
          2.0880e-01, 5.4954e-01],
         [9.2964e-01, 7.7557e-01, 6.9742e-01,  ..., 2.3693e-01,
          2.8103e-01, 7.5568e-01],
         [8.5465e-01, 6.3558e-02, 5.7052e-01,  ..., 5.6410e-01,
          5.1641e-01, 6.5736e-01],
         ...,
         [5.7732e-01, 7.9206e-01, 3.0337e-02,  ..., 3.0186e-01,
          5.313

### INDEXING

In [177]:
# Selecting Data from tensors with indexing (similar to Numpy indexing)

import torch

x = torch.arange(1,10).reshape(1,3,3)
x, x.shape
# (tensor([[[1, 2, 3],
#           [4, 5, 6],
#           [7, 8, 9]]]),
#  torch.Size([1, 3, 3]))

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [181]:
x[0], x[0][1], x[0][1][2]
# (tensor([[1, 2, 3],
#          [4, 5, 6],
#          [7, 8, 9]]),
#  tensor([4, 5, 6]),
#  tensor(6))

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([4, 5, 6]),
 tensor(6))

In [211]:
# Convert data from Numpy to Tensor
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor
# tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)
# Be careful. Numpy default datatype is float 64, but pytorch is float32

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [212]:
array = array + 1
array, tensor
# (array([2., 3., 4., 5., 6., 7., 8.]),  They do not share memory
#  tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [213]:
#Tensor to NumPy array
tensor = torch.ones(7)  #default dtype is float32
numpy_tensor = tensor.numpy()
tensor, numpy_tensor
# (tensor([1., 1., 1., 1., 1., 1., 1.]),
#  array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))  data type is transferred

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [214]:
#Changing the tensor, what happens to numpy_tensor?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility

In [270]:
# Creating random but reproducible tensors
RANDOM_SEED = 43  #think of as a different "flavor" of randomness
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)     #Call each time you need a random seed
random_tensor_D = torch.rand(3,4)

random_tensor_C, random_tensor_D
# tensor([[True, True, True, True],
#         [True, True, True, True],
#         [True, True, True, True]])

(tensor([[0.4540, 0.1965, 0.9210, 0.3462],
         [0.1481, 0.0858, 0.5909, 0.0659],
         [0.7476, 0.6253, 0.9392, 0.1338]]),
 tensor([[0.4540, 0.1965, 0.9210, 0.3462],
         [0.1481, 0.0858, 0.5909, 0.0659],
         [0.7476, 0.6253, 0.9392, 0.1338]]))

In [271]:
# Check for GPU access with PyTorch
torch.cuda.is_available()
#False (current pc doesn't have a GPU)

False

In [272]:
# set device to default to the CPU if we don't have a GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

'cpu'

In [273]:
tensor = torch.tensor([1,2,3])

print(tensor, tensor.device)
#tensor([1, 2, 3]) cpu

tensor([1, 2, 3]) cpu


In [275]:
# "to" keyword changes device tensor runs on
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor_on_gpu.device
#(tensor([1, 2, 3]), device(type='cpu')) would be GPU if we had one

(tensor([1, 2, 3]), device(type='cpu'))

In [276]:
#Move tensor back to CPU (for Numpy computations)
tensor_on_gpu = tensor_on_gpu.to('cpu')
tensor_on_gpu

tensor([1, 2, 3])

In [289]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
x = torch.rand(7,7)
torch.manual_seed(RANDOM_SEED)
y = torch.rand(1,7)

torch.mm(x, y.transpose(0,1))

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [291]:
RANDOM_SEED = 7

torch.manual_seed(RANDOM_SEED)
x = torch.rand(1,1,1,10)
x.squeeze()

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])