In [46]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)
import random

2.7.1+cpu


In [2]:
#init a tensor (scalar)
scalar = torch.tensor(7)
scalar
#Returns tensor(7)

tensor(7)

In [3]:
scalar.ndim
#returns 0, it is a 0 dimensional vector

0

In [ ]:
scalar.item()
# returns 7. Get tensor back as python int

In [4]:
#Vector
vector = torch.tensor([7,7])
vector
#tensor([7, 7])

tensor([7, 7])

In [5]:
vector.ndim
# returns 1. think of dimensions of a tensor as the number of nested square brackets

1

In [6]:
vector.shape
#torch.Size([2])

torch.Size([2])

In [8]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX.shape, MATRIX.ndim
#(torch.Size([2, 2]), 2)

(torch.Size([2, 2]), 2)

In [16]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,5,4]],
                       [[5,6,8],
                        [9,10,11],
                        [13,14,15]]])
TENSOR.shape, TENSOR.ndim
#(torch.Size([1, 3, 3]), 3)

(torch.Size([2, 3, 3]), 3)

In [17]:
TENSOR


tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [ 2,  5,  4]],

        [[ 5,  6,  8],
         [ 9, 10, 11],
         [13, 14, 15]]])

### CH13 - Creating Random Tensors




In [26]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor
#0.00333,0.83908,0.47228,0.84238
#0.69856,0.58338,0.54370,0.24816
#0.52106,0.59562,0.00936,0.40265



tensor([[0.5998, 0.8659, 0.7958, 0.5642],
        [0.4093, 0.5566, 0.4842, 0.3007],
        [0.4343, 0.6334, 0.5090, 0.4333]])

In [24]:
# Create a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, color channels (RGB)
random_image_size_tensor.shape, random_image_size_tensor.ndim
# (torch.Size([224, 224, 3]), 3)

(torch.Size([224, 224, 3]), 3)

In [28]:
# Tensor of Zeros and Ones
zero = torch.zeros(size=(3,4))
zero
# 0.00000,0.00000,0.00000,0.00000
# 0.00000,0.00000,0.00000,0.00000
# 0.00000,0.00000,0.00000,0.00000



tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [29]:
# Anything multiplied by zero matrix is 0 matrix
zero * random_tensor
# 0.00000,0.00000,0.00000,0.00000
# 0.00000,0.00000,0.00000,0.00000
# 0.00000,0.00000,0.00000,0.00000


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
# Anything Multiplied by a one matrix is itself
ones = torch.ones(size=(3,4))
ones
# 1.00000,1.00000,1.00000,1.00000
# 1.00000,1.00000,1.00000,1.00000
# 1.00000,1.00000,1.00000,1.00000

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [33]:
# default data type is torch.float32
ones.dtype
#torch.float32

torch.float32

In [37]:
# Use torch.arange() to create a tensor of len 10 in order
one_to_ten = torch.arange(0,10)
# tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
torch.arange(start=0, end=77, step=11)
# tensor([ 0, 11, 22, 33, 44, 55, 66])

tensor([ 0, 11, 22, 33, 44, 55, 66])

In [47]:
# Creating tensors like (copy attributes of another tensor)
ten_zeros = torch.full_like(input = one_to_ten, fill_value = random.randint(0,5))
ten_zeros
# tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [49]:
# Float 32 tensor is default data type
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None,        # Data Type (int, float32, float16, etc)
                               device=None,         # Default is CPU
                               requires_grad=False) # Track the gradient of the tensor as it goes through certain operations. worry about later
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [50]:
# Refactor float_32 tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor
# tensor([3., 6., 9.], dtype=torch.float16)

tensor([3., 6., 9.], dtype=torch.float16)

In [52]:
# multiplying a 16 x 32 converts the output to a 32
x = float_16_tensor * float_32_tensor
x, x.dtype
# (tensor([ 9., 36., 81.]), torch.float32)

(tensor([ 9., 36., 81.]), torch.float32)

In [56]:
# Operations on different dtypes doesnt always work
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [57]:
# Getting Information from tensors
# e.g. Shape, Datatype, and Device
float_16_tensor.shape, float_16_tensor.ndim, float_16_tensor.device
# (torch.Size([3]), 1, device(type='cpu'))

(torch.Size([3]), 1, device(type='cpu'))

In [63]:
some_tensor = torch.rand(3,4, dtype=torch.float16)
some_tensor
# 0.96271,0.78899,0.16476,0.17654
# 0.40736,0.24902,0.94571,0.67510
# 0.79564,0.68495,0.79836,0.89421


tensor([[0.1147, 0.0908, 0.9941, 0.5654],
        [0.7910, 0.7114, 0.4102, 0.7378],
        [0.3735, 0.0137, 0.2505, 0.8555]], dtype=torch.float16)

In [64]:
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")
# Datatype of tensor: torch.float32
# Shape of tensor: torch.Size([3, 4])
# Device of tensor: cpu

Datatype of tensor: torch.float16
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


In [66]:
tensor = torch.tensor([1,2,3])
tensor + 10, tensor + 100
# (tensor([11, 12, 13]), tensor([101, 102, 103]))

(tensor([11, 12, 13]), tensor([101, 102, 103]))

In [70]:
tensor * 10, (tensor * 10)// 2, tensor - 10
# (tensor([10, 20, 30]), tensor([ 5, 10, 15]), tensor([-9, -8, -7]))

(tensor([10, 20, 30]), tensor([ 5, 10, 15]), tensor([-9, -8, -7]))

In [71]:
#In-built functions. Usually just use python operators
torch.mul(tensor, 10), torch.add(tensor,10)
#(tensor([10, 20, 30]), tensor([11, 12, 13]))

(tensor([10, 20, 30]), tensor([11, 12, 13]))

In [72]:
# Matrix Multiplication (element wise)
print(tensor, "*", tensor, "=", tensor * tensor)
# tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])

tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


In [73]:
# Normal Matrix Multiplication (matmul)
torch.matmul(tensor, tensor)
# tensor(14)

tensor(14)

In [138]:
#Remember inner dimensions must match, result is the outer dimensions
x,y = torch.rand(4,3),torch.rand(3,2)
z = torch.matmul(x,y)
z.shape, z.ndim
#(torch.Size([4, 2]), 2)

(torch.Size([4, 2]), 2)

In [147]:
#Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.mm(tensor_A, tensor_B)   #torch.mm is the same as torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [148]:
# A Transpose switches the dimensions of a matrix
tensor_B.T
# 7,8,9
# 10,11,12


tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [149]:
# We can now multiply A and B
torch.mm(tensor_A, tensor_B.T)
# 27,30,33
# 61,68,75
# 95,106,117


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [152]:
x = torch.arange(0,100,10)
torch.min(x), torch.max(x), torch.mean(x), torch.sum(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [153]:
x.dtype
#torch.int64

torch.int64

In [154]:
torch.mean(x.type(torch.float32))
#tensor(45.)   now it works

tensor(45.)

In [155]:
x = torch.arange(0,100,10)
torch.min(x), torch.max(x), torch.mean(x.type(torch.float32)), torch.sum(x)
#(tensor(0), tensor(90), tensor(45.), tensor(450))

(tensor(0), tensor(90), tensor(45.), tensor(450))

In [158]:
# Find the index of the min and max with argmin and argmax
torch.argmin(x.type(torch.float32)), torch.argmax(x.type(torch.float32))
#(tensor(0), tensor(9))

(tensor(0), tensor(9))

In [176]:
x = torch.arange(1., 10.)
x, x.shape
# (tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [168]:
# dimensions must be compatible with original dimensions
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape
# (tensor([[1., 2., 3.],
#          [4., 5., 6.],
#          [7., 8., 9.]]),
#  torch.Size([3, 3]))

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [171]:
# Change the view (similar to reshape. however, z shares memory with x)
# thus, changing z changes x
z = x.view(3,3)
z, z.shape
# (tensor([[1., 2., 3.],
#          [4., 5., 6.],
#          [7., 8., 9.]]),
#  torch.Size([3, 3]))

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [184]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked
# 1.00000,2.00000,3.00000,4.00000,5.00000,6.00000,7.00000,8.00000,9.00000
# 1.00000,2.00000,3.00000,4.00000,5.00000,6.00000,7.00000,8.00000,9.00000
# 1.00000,2.00000,3.00000,4.00000,5.00000,6.00000,7.00000,8.00000,9.00000
# 1.00000,2.00000,3.00000,4.00000,5.00000,6.00000,7.00000,8.00000,9.00000


tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])